image:
  name: vault:latest

stages:
  - checkvars
  - readsecret

print variables:
  stage: checkvars
  environment:
    name: DEMOSTACK
  before_script:
    - export VAULT_ADDR=$VAULT_SERVER_URL
    - export VAULT_NAMESPACE=""
    - export VAULT_TOKEN="$(vault write -field=token auth/$VAULT_AUTH_PATH/login role=$VAULT_AUTH_ROLE jwt=$CI_JOB_JWT)"
    - export VAULT_SECRET="$(vault kv get -field=foo kv/test)"
  script:
    - echo $VAULT_ADDR
    - echo $VAULT_NAMESPACE
    - echo $VAULT_SECRET

read secret:
  stage: readsecret
  environment:
    name: DEMOSTACK
  secrets:
    MY_SECRET_1:
      vault: test/foo@kv
      file: false
      # test - The secret
      # foo - The field
      # kv - The path where the secrets engine is mounted
    MY_SECRET_2:
      vault:
        engine:
          name: kv-v2
          path: kv
        path: test
        field: foo
      file: true 
  script:
    - echo $VAULT_SERVER_URL
    - echo $VAULT_AUTH_ROLE
    - echo $VAULT_AUTH_PATH
    - echo $VAULT_NAMESPACE
    - echo $MY_SECRET_1
    - cat $MY_SECRET_2
